const carsData = [
  {
    id: 1,
    brand: "BMW",
    name: "M4 Competition",
    year: 2024,
    type: "Sport",
    price: 85000,
    mileage: 0,
    engine: "3.0L Twin-Turbo I6",
    horsepower: 503,
    transmission: "8-Speed Automatic",
    color: "Brooklyn Grey",
    fuel: "Petrol",
    seats: 4,
    image: "https://cdn.motor1.com/images/mgl/P33oZ/s3/2021-bmw-m4-competition.jpg",
    badge: "New Arrival",
    badgeClass: "badge-new",
    description: "The BMW M4 Competition is the pinnacle of performance engineering. With a 503hp twin-turbo engine, M xDrive all-wheel-drive, and a refined interior packed with tech, it delivers supercar thrills in a usable everyday package.",
    features: ["Head-Up Display", "Harman Kardon Sound", "M Carbon Seats", "Adaptive M Suspension", "Wireless CarPlay"]
  },
  {
    id: 2,
    brand: "Mercedes",
    name: "C-Class C300",
    year: 2024,
    type: "Luxury",
    price: 55000,
    mileage: 0,
    engine: "2.0L Turbo I4",
    horsepower: 255,
    transmission: "9-Speed Automatic",
    color: "Obsidian Black",
    fuel: "Petrol",
    seats: 5,
    image: "https://cdn.motor1.com/images/mgl/nNM4P/s3/2022-mercedes-benz-c-class.jpg",
    badge: "Best Seller",
    badgeClass: "badge-hot",
    description: "The new Mercedes C-Class sets the bar for the luxury sedan segment. Its stunning interior is inspired by the flagship S-Class and packs cutting-edge technology with a smooth, refined drive.",
    features: ["MBUX Infotainment", "Panoramic Sunroof", "Burmester Sound", "64-Color Ambient Lighting", "Driver Assistance Package"]
  },
  {
    id: 3,
    brand: "Porsche",
    name: "Cayenne GTS",
    year: 2023,
    type: "SUV",
    price: 120000,
    mileage: 8000,
    engine: "4.0L Twin-Turbo V8",
    horsepower: 460,
    transmission: "8-Speed PDK",
    color: "Carmine Red",
    fuel: "Petrol",
    seats: 5,
    image: "https://cdn.motor1.com/images/mgl/nNMBP/s3/2023-porsche-cayenne-gts.jpg",
    badge: "Low Mileage",
    badgeClass: "badge-low",
    description: "The Porsche Cayenne GTS combines the practicality of a premium SUV with the performance DNA of a true sports car. The twin-turbo V8 launches it to 100km/h in just 4.5 seconds.",
    features: ["Sport Chrono Package", "PASM Air Suspension", "Bose Surround Sound", "Night Vision Assist", "Panoramic Roof System"]
  },
  {
    id: 4,
    brand: "Toyota",
    name: "Land Cruiser 300",
    year: 2023,
    type: "SUV",
    price: 90000,
    mileage: 15000,
    engine: "3.5L Twin-Turbo V6",
    horsepower: 409,
    transmission: "10-Speed Automatic",
    color: "Platinum White Pearl",
    fuel: "Petrol",
    seats: 7,
    image: "https://cdn.motor1.com/images/mgl/ZnnqP/s3/2022-toyota-land-cruiser.jpg",
    badge: "7 Seats",
    badgeClass: "badge-new",
    description: "The legendary Toyota Land Cruiser 300 Series — more capable, more refined, and more efficient than ever. Whether navigating Cairo traffic or Egypt's desert terrain, this is the ultimate all-terrain companion.",
    features: ["Kinetic Dynamic Suspension", "Multi-Terrain Select", "7-Seat Leather Interior", "JBL Premium Audio", "360-Degree Camera"]
  },
  {
    id: 5,
    brand: "Audi",
    name: "A6 Quattro",
    year: 2024,
    type: "Sedan",
    price: 62000,
    mileage: 0,
    engine: "3.0L TFSI V6",
    horsepower: 335,
    transmission: "7-Speed S Tronic",
    color: "Navarra Blue Metallic",
    fuel: "Petrol",
    seats: 5,
    image: "https://cdn.motor1.com/images/mgl/nNMLP/s3/2020-audi-a6.jpg",
    badge: "New Arrival",
    badgeClass: "badge-new",
    description: "The Audi A6 is a masterclass in understated luxury. Its Virtual Cockpit Pro, quattro all-wheel-drive, and refined cabin make every journey feel special — whether a morning commute or a long-distance trip.",
    features: ["Audi Virtual Cockpit Pro", "Matrix LED Headlights", "Bang and Olufsen 3D Sound", "Quattro AWD", "Adaptive Cruise Assist"]
  },
  {
    id: 6,
    brand: "Hyundai",
    name: "Tucson N-Line",
    year: 2024,
    type: "SUV",
    price: 28000,
    mileage: 0,
    engine: "1.6L Turbo I4",
    horsepower: 180,
    transmission: "7-Speed DCT",
    color: "Shimmering Silver",
    fuel: "Petrol",
    seats: 5,
    image: "https://cdn.motor1.com/images/mgl/nNMEP/s3/2022-hyundai-tucson-n-line.jpg",
    badge: "Great Value",
    badgeClass: "badge-low",
    description: "The Hyundai Tucson N-Line brings sporty styling and impressive value to the competitive compact SUV segment. With its bold grille, turbo engine, and well-equipped interior, it is the smart choice.",
    features: ["10.25in Touchscreen", "Digital Cluster", "Blind-Spot Collision Warning", "Safe Exit Assist", "Wireless Charging"]
  },
  {
    id: 7,
    brand: "Ford",
    name: "Mustang GT",
    year: 2023,
    type: "Sport",
    price: 42000,
    mileage: 5000,
    engine: "5.0L V8",
    horsepower: 450,
    transmission: "6-Speed Manual",
    color: "Grabber Blue",
    fuel: "Petrol",
    seats: 4,
    image: "https://cdn.motor1.com/images/mgl/YnnqP/s3/2023-ford-mustang-gt.jpg",
    badge: "Collectors Pick",
    badgeClass: "badge-hot",
    description: "The Ford Mustang GT — an American icon. The thunderous 5.0L Coyote V8 produces 450hp and delivers a visceral driving experience that no other car in this price range can match.",
    features: ["5.0L Coyote V8", "Brembo Brakes", "MagneRide Suspension", "SYNC 4 Infotainment", "Launch Control"]
  },
  {
    id: 8,
    brand: "Mercedes",
    name: "GLE 450 AMG",
    year: 2023,
    type: "Luxury",
    price: 95000,
    mileage: 12000,
    engine: "3.0L Inline-6 Mild Hybrid",
    horsepower: 362,
    transmission: "9-Speed Automatic",
    color: "Diamond White",
    fuel: "Hybrid",
    seats: 5,
    image: "https://cdn.motor1.com/images/mgl/nNMRP/s3/2023-mercedes-benz-gle.jpg",
    badge: "Hybrid",
    badgeClass: "badge-new",
    description: "The Mercedes GLE 450 AMG-Line offers executive SUV presence with the efficiency of mild-hybrid technology. Its E-Active Body Control suspension delivers a magic-carpet ride while the AMG styling turns heads.",
    features: ["E-Active Body Control", "MBUX with Augmented Reality", "Burmester Surround Sound", "Parking Package Pro", "AMG Styling Package"]
  }
];